### ISSUE TITLE
Deprecated in 3.1: elgg_register_css is deprecated

### ISSUE THREAD

**Issue by rohit1290** [ColdTrick/icon_cropper#1]
https://github.com/ColdTrick/icon_cropper/blob/2f4d6ec1ea0ac01e07ae14b004eac57211190c94/classes/ColdTrick/IconCropper/Bootstrap.php#L15

**Comment by jeabakker** [comment]
correct however the icon cropper functionality was moved into Elgg core, so not going to fix this

**Comment by rohit1290** [comment]
ohh.. I did not knew this.. in that case I will remove this plugin.. (y)
Thanks for the info.

**Comment by jeabakker** [comment]
> ohh.. I did not knew this

We did mention it in the release notes https://elgg.org/blog/view/2951226/elgg-31-released ;)

**Comment by rohit1290** [comment]
> We did mention it in the release notes https://elgg.org/blog/view/2951226/elgg-31-released ;)

Yup saw that just now.. 
Elgg 3.1 required php 7.1 and my old server was not supporting it.. So i migrated to a new server and made a jump from 3.0.6 to 3.1.3. It was my bad that i did not read the release note for 3.1 to 3.1.2
